# Generated by Django 3.0.4 on 2020-03-22 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Grupos',
            },
        ),
        migrations.CreateModel(
            name='Subgrupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recurso.Grupo', verbose_name='Categoría')),
            ],
            options={
                'verbose_name_plural': 'Subgrupos',
            },
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recurso.Grupo')),
                ('subgrupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recurso.Subgrupo')),
            ],
            options={
                'verbose_name_plural': 'Recursos',
            },
        ),
    ]
