# Generated by Django 3.0.4 on 2020-03-22 16:44

import apps.recurso.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recurso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to=apps.recurso.models.upload_path_handler),
        ),
        migrations.AddField(
            model_name='recurso',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
    ]
