# Generated by Django 3.0.4 on 2020-03-21 12:12

import apps.home.models
import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('home', 'Inicio'), ('nav', 'Nav'), ('slides', 'Slides'), ('welcome', 'Welcome'), ('works', 'Works'), ('counter', 'Counter'), ('services', 'Services'), ('blog', 'Blog'), ('team', 'Team'), ('testimony', 'Testimony'), ('subscribe', 'Subscribe'), ('footer', 'Footer')], default='home', max_length=15, verbose_name='Sección')),
                ('label', models.CharField(max_length=50, verbose_name='Etiqueta')),
                ('link', models.CharField(blank=True, max_length=100, null=True)),
                ('text_short', models.CharField(blank=True, max_length=254, null=True, verbose_name='Texto breve')),
                ('text_large', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Texto largo')),
                ('image', models.FileField(blank=True, null=True, upload_to=apps.home.models.upload_path_handler)),
                ('ordered', models.SmallIntegerField(blank=True, default=1, null=True, verbose_name='Ordenación')),
                ('active', models.BooleanField(blank=True, default=1, null=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'unique_together': {('section', 'label')},
            },
        ),
    ]
