# Generated by Django 3.0.4 on 2020-03-21 12:12

import apps.blog.models
import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name_plural': 'Etiquetas',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('title', models.CharField(max_length=50, verbose_name='Título')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Contenido')),
                ('background_image', models.FileField(blank=True, null=True, upload_to=apps.blog.models.upload_post_path_handler, verbose_name='Imágen')),
                ('created_on', models.DateField(auto_now_add=True, verbose_name='Creado')),
                ('updated_on', models.DateField(auto_now=True, verbose_name='Modificado')),
                ('publish_on', models.DateField(blank=True, null=True, verbose_name='Publicado ')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Category', verbose_name='Categoría')),
                ('tags', models.ManyToManyField(blank=True, null=True, to='blog.Tag')),
            ],
            options={
                'verbose_name_plural': 'Artículos',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_author', models.CharField(max_length=50, verbose_name='Nombre')),
                ('comment_content', models.CharField(max_length=200, verbose_name='Cometario')),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_comments', to='blog.Post', verbose_name='Artículo')),
            ],
            options={
                'verbose_name_plural': 'Comentarios',
                'ordering': ['-comment_date'],
            },
        ),
    ]
