# Generated by Django 2.2.5 on 2020-03-04 12:44

import apps.blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200303_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='background_image',
            field=models.FileField(blank=True, null=True, upload_to=apps.blog.models.upload_post_path_handler),
        ),
    ]
